service: serverless-starter-kit

frameworkVersion: ">=1.1.0 <=2.69.1"

plugins:
  - serverless-export-env

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  httpApi:
    cors:
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedOrigins:
        - ${env:AUTH0_ALLOWED_ORIGIN}
    authorizers:
      auth0Authorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${env:AUTH0_ISSUE_URL}
        audience: ${env:AUTH0_AUDIENCE}
  logs:
    httpApi: true

functions:
  create:
    handler: todos/create.create
    events:
      - httpApi:
          path: /todos
          method: POST
          authorizer:
            name: auth0Authorizer

  list:
    handler: todos/list.list
    events:
      - httpApi:
          path: /todos
          method: GET
          authorizer:
            name: auth0Authorizer

  get:
    handler: todos/get.get
    events:
      - httpApi:
          path: /todos/{id}
          method: GET
          authorizer:
            name: auth0Authorizer

  update:
    handler: todos/update.update
    events:
      - httpApi:
          path: /todos/{id}
          method: PUT
          authorizer:
            name: auth0Authorizer

  delete:
    handler: todos/delete.delete
    events:
      - httpApi:
          path: /todos/{id}
          method: DELETE
          authorizer:
            name: auth0Authorizer

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}